/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2023 Kagati Foundation
 */

#ifndef IPV6_PARSER_H
#define IPV6_PARSER_H

#include <stdint.h>

#include "proto_node.h"
#include "hex.h"
#include "ip.h"
#include "raw_stream.h"

#define IPV6_HEADER_LEN				40 /* 40-bytes */

#define IPV6_EXT_HOP_BY_HOP 		0
#define IPV6_EXT_ROUTING			43
#define IPV6_EXT_FRAGMENT			44
#define IPV6_EXT_AUTH_HDR			51 // Authentication Header
#define IPV6_EXT_ESP				50 // Encapsulating Security Payload
#define IPV6_EXT_DEST_OPTS			60 // Destination Options
#define IPV6_EXT_MOBILITY			135

/**
 * IPv6 extension header structure.
 */
typedef struct __attribute__((packed)) IPV6ExtHeader {
    uint8_t next_hdr; 		/* Next header */
    uint8_t hdr_ext_len; 	/* Header extension length */
} IPV6ExtHeader_t;

typedef struct __attribute__((packed)) IPV6ExtHeaderChain {
	ProtocolNode_t* last_node; /* The last header in the extension chain */
	uint8_t			next_proto;
	size_t			offset;
} IPV6ExtHeaderChain_t;

/**
 * IPv6 header structure.
 */
typedef struct __attribute__((packed)) IPV6Header {
	uint32_t 	ver_tc_fl; 				/* Version(4 bits), Traffic Class(6+2 bits), and Flow Label(20 bits) */
	uint16_t 	len;       				/* Payload length */
	uint8_t 	next_hdr;  				/* This field usually specifies the transport layer protocol used by a packet's payload. */
	uint8_t 	hop_limit; 				/* Replaces the time to live field in IPv4 */
	uint8_t 	src[IPV6_ADDR_LEN];   	/* Source address */
	uint8_t 	dst[IPV6_ADDR_LEN];   	/* Destination address */
} IPV6Header_t;

// IPv6 extension headers

/**
 * === Fragment header (fixed 8 bytes) ===
 * Next header: 8 bits
 * 	- Identifies the type of the next header.
 * 
 * Reserved: 8 bits; Reserved == 0
 *	- Initialized to all zeroes.
 *
 * Fragment offset: 13 bits
 *	- Offset, in 8-octet units, relative to the start of the fragmentable 
 *  part of the original packet.
 * 
 * Reserved2 (Res): 2 bits; Res == 0
 * 
 * Reserved; initialized to zeroes.
 * 
 * M Flag (M): 1 bit
 * 	- 1 means more fragments follow; 0 means last fragment.
 * 
 * Identification: 32 bits
 *  - Packet identification value, generated by the source node. Needed for 
 *  reassembly of the original packet.
 */
typedef struct __attribute__((packed)) IPV6ExtFragment {
    uint8_t 	next_hdr;
    uint8_t 	reserved; // 0
    uint16_t 	frag_offset_m;
    uint32_t 	identification;
} IPV6ExtFragment_t;

/**
 * === Hop-by-hop options and destination options === 
 * Next Header: 8 bits
 * - Specifies the type of the next header.
 * 
 * Header extension length: 8 bits
 *  - Length of this header in 8-octet units, not including the first 8 octets.
 * 
 * Options and padding: variable
 *  - Contains one or more options, and optional padding fields to align options and 
 *  to make the total header length a multiple of 8 octets. Options are TLV-coded.
 */
typedef struct __attribute__((packed)) IPV6ExtOptions {
    uint8_t 	next_hdr;
    uint8_t 	hdr_ext_len;
    uint8_t* 	options;
} IPV6ExtOptions_t;

/**
 * === Routing header (variable length) ===
 * Next Header: 8 bits
 * - Specifies the type of the next header.
 * 
 * Header extension length: 8 bits
 *  - Length of this header in 8-octet units, not including the first 8 octets.
 * 
 * Routing type: 8 bits
 * - A value between 0 and 255, as assigned by IANA.
 * 
 * Segments Left: 8 bits
 * - Number of nodes this packet still has to visit before reaching its final destination.
 * 
 * Type-specific Data: variable
 * - Data that belongs to this type of routing header.
 */
typedef struct __attribute__((packed)) IPV6ExtRouting {
    uint8_t 	next_hdr;
    uint8_t 	hdr_ext_len;
    uint8_t 	routing_type;
    uint8_t 	segments_left;
    uint8_t* 	data;
} IPV6ExtRouting_t;

// sanity checks
_Static_assert(sizeof(IPV6Header_t) == 40, "IPV6Header_t's length must be 40 bytes");

HEX_P ProtocolNode_t* parse_ipv6_packet(struct raw_pack_stream*);

HEX_P inline uint8_t ipv6_version(const IPV6Header_t*);

HEX_P inline uint8_t ipv6_traffic_class(const IPV6Header_t*);

HEX_P inline uint32_t ipv6_flow_label(const IPV6Header_t*);

#endif
